basePath: /app
definitions:
  handler.DeleteNoteResponse:
    properties:
      message:
        type: string
    type: object
  handler.GetNotesResponse:
    properties:
      message:
        type: string
      payload:
        items:
          $ref: '#/definitions/handler.Note'
        type: array
    type: object
  handler.Note:
    properties:
      created_at:
        type: string
      id:
        type: string
      text:
        type: string
    type: object
  handler.PostNoteRequest:
    properties:
      text:
        type: string
    type: object
  handler.PostNoteResponse:
    properties:
      message:
        type: string
      payload:
        $ref: '#/definitions/handler.Note'
    type: object
info:
  contact: {}
  description: This is a sample server for a App application.
  title: App API
  version: "1.0"
paths:
  /v1/notes:
    get:
      consumes:
      - application/json
      description: Get a list of all notes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetNotesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GetNotesResponse'
      summary: List Notes
      tags:
      - v1
    post:
      consumes:
      - application/json
      description: Create a new note
      parameters:
      - description: Note text
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.PostNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PostNoteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.PostNoteResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.PostNoteResponse'
      summary: Create Note
      tags:
      - v1
  /v1/notes/{note_id}:
    delete:
      consumes:
      - application/json
      description: Delete a note by ID
      parameters:
      - description: Note ID
        in: path
        name: note_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteNoteResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.DeleteNoteResponse'
      summary: Delete Note
      tags:
      - v1
swagger: "2.0"
