// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/grpc/handler/dependency.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapter/grpc/handler/dependency.go -destination=internal/adapter/grpc/handler/dependency_mock_test.go -package=handler_test
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/jian-hua-he/reference-app/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteApp is a mock of NoteApp interface.
type MockNoteApp struct {
	ctrl     *gomock.Controller
	recorder *MockNoteAppMockRecorder
	isgomock struct{}
}

// MockNoteAppMockRecorder is the mock recorder for MockNoteApp.
type MockNoteAppMockRecorder struct {
	mock *MockNoteApp
}

// NewMockNoteApp creates a new mock instance.
func NewMockNoteApp(ctrl *gomock.Controller) *MockNoteApp {
	mock := &MockNoteApp{ctrl: ctrl}
	mock.recorder = &MockNoteAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteApp) EXPECT() *MockNoteAppMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNoteApp) Create(ctx context.Context, text string) (*entity.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, text)
	ret0, _ := ret[0].(*entity.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNoteAppMockRecorder) Create(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNoteApp)(nil).Create), ctx, text)
}

// Delete mocks base method.
func (m *MockNoteApp) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNoteAppMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNoteApp)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockNoteApp) List(ctx context.Context) ([]entity.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNoteAppMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNoteApp)(nil).List), ctx)
}
